/*
** Inserted at beginning of c files generated by flex
** REMEMBER:  Change flex.reset too.
*/

/*@-allmacros@*/
/*@-pred@*/
/*@-globstate@*/
/*@-null@*/
/*@+boolint@*/
/*@+charint@*/
/*@-macrospec@*/
/*@-macroredef@*/
/*@-exitarg@*/
/*@-compdef@*/
/*@-uniondef@*/
/*@+ignorequals@*/
/*@-noreturn@*/
/*@-mustfree@*/
/*@-compdestroy@*/
/*@-branchstate@*/
/*@-unreachable@*/
/*@-varuse@*/
/*@-fcnuse@*/
/*@-exportlocal@*/
/*@-evalorderuncon@*/
/*@-exportheader@*/
/*@-redecl@*/
/*@-loopswitchbreak@*/
/*@-switchswitchbreak@*/
/*@-sizeoftype@*/
/*@-czechfcns@*/
/*@-noparams@*/
/*@-ansireserved@*/
/*@-ifblock@*/
/*@-whileblock@*/
/*@-forblock@*/
/*@-elseifcomplete@*/
/*@+ptrnegate@*/
/*@-onlytrans@*/
/*@-temptrans@*/
/*@-immediatetrans@*/
/*@-namechecks@*/
/*@+matchanyintegral@*/
/*@-statictrans@*/
/*@-compmempass@*/
/*@-forempty@*/
/*@-evalorder@*/
/*@-retalias@*/
/*@-dependenttrans@*/
/*@-noeffect@*/
/*@-protoparammatch@*/
/*@-casebreak@*/
/*@-retvalother@*/
/*@-exportheader@*/

/*drl added 11/27/2001*/


# ifdef __LCLINT__
/*@-redecl@*/ /*@-type@*/
extern int cgrammar_lsllex (void);
/*@=redecl@*/ /*@=type@*/

/*
** Need to do this because ECHO is defined by the Posix library.  
** flex shouldn't use it.
*/

/*@notfunction@*/
# define ECHO \
  fwrite (yytext, yyleng, 1, yyout)

# ifndef DEFFILENO
extern /*@external@*/ int fileno (/* FILE *stream */);
# define DEFFILENO
# endif
# endif

# ifdef OSF
# undef __GNUC__ 
# endif

/*@-redecl@*/

/* < end of flex.head > */

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 189
#define YY_END_OF_BUFFER 190
static yyconst short int yy_accept[574] =
    {   0,
        0,    0,  190,  188,  167,  168,  155,  188,    3,   88,
      161,  154,  188,  149,  150,  159,  158,  146,  157,  153,
      160,  103,  103,  147,  143,  162,  148,  163,  166,  188,
       88,   88,  151,  187,  152,  164,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,  144,  165,
      145,  156,  142,    0,   43,    0,    2,   88,  127,  185,
      186,  136,  128,    0,    0,  125,  133,  123,  134,  124,
      135,    0,  117,    1,  126,  138,  120,   96,    0,  105,
      104,    0,  103,  132,  139,  141,  140,  131,    0,    0,

        0,    0,    0,   88,  129,   88,   88,   88,   88,   88,
       88,   88,   88,    9,   88,   88,   88,   88,   88,   88,
       88,   13,   46,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,  130,  137,    0,    0,    2,  110,    4,    0,
      115,  116,  117,    0,  118,  119,   98,   97,    0,  114,
      106,  107,  107,   89,  122,  121,  175,  176,  173,  178,
      183,  174,  184,  179,  182,  177,  180,  181,    0,    0,
        0,   44,    0,    0,    0,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   11,   88,   88,   27,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   45,   88,
       88,   88,   88,   88,   88,   88,   78,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,    0,   43,
        0,    0,  117,    0,  115,  116,    0,  120,   99,  100,
      100,  112,  113,  109,  108,   90,   92,  171,  172,    0,
        0,    0,    0,  111,   88,   88,   88,   88,   40,   88,
        6,   29,   88,   88,   88,   88,   88,   88,   10,   25,

       88,   88,   88,   88,   12,   88,   88,   88,   53,   88,
       31,   88,   88,   88,   88,   54,   88,   88,   72,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   26,   88,   88,   88,    0,
      117,  102,  101,   91,   93,   93,    0,  170,    0,   44,
        0,   88,   88,   88,   88,    5,   88,   36,   88,   88,
       88,   88,   88,   88,   88,   30,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   73,
       88,   88,   88,   88,   88,   88,   88,   88,   32,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   81,
       24,   88,   88,   88,   88,   88,   18,   80,   95,   94,
      169,   88,   84,   88,   88,   88,   88,   88,   88,   88,
       28,   88,   39,   88,   21,   88,   56,   82,   88,   88,
       86,   64,   88,   88,   88,   88,   88,   88,   88,   88,
       62,   88,   88,   14,   79,   34,   15,   88,   42,   22,
       17,   88,   88,   88,   88,   88,   76,   19,   20,   88,
       85,   38,   49,   68,   88,   88,    8,   88,   63,   88,
       88,   88,   66,   87,   55,   88,   88,   88,   88,   47,
       88,   88,   61,   88,   88,   48,   65,   88,   23,   88,

       88,   88,   88,   69,    7,   88,   77,   88,   88,   88,
       88,   74,   16,   88,   41,   37,   88,   57,   88,   33,
       35,   88,   75,   58,   88,   88,   88,   88,   88,   88,
       71,   88,   88,   88,   88,   88,   88,   67,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   50,   88,
       88,   59,   88,   88,   70,   88,   60,   88,   88,   83,
       88,   88,   88,   88,   88,   88,   88,   88,   52,   88,
       88,   51,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   30,   32,   33,
       34,    8,    8,    8,   35,   36,   37,    8,    8,    8,
       38,   39,   40,   41,   42,    8,   43,   44,    8,   45,
       46,   47,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,    8,   60,   61,   62,   63,
       64,   65,    8,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[79] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    2,
        5,    5,    5,    5,    5,    5,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[584] =
    {   0,
        0,    0,  748,  749,  749,  749,  722,   73,    0,    0,
       55,   71,  699,  749,  749,  720,   67,  749,   68,   66,
       74,   80,   87,  749,  749,   65,  719,   77,  749,   99,
       98,  692,  749,  749,  749,  717,  691,   28,  674,   67,
       51,   73,   82,  675,   84,   55,  674,  686,   89,   98,
      685,  680,  105,  102,  671,   62,  675,  673,  749,   86,
      749,  749,  749,  132,  175,  728,    0,    0,  749,  749,
      749,  749,  749,  144,  163,  749,  749,  749,  749,  749,
      749,  712,  151,  749,  749,  749,  165,  172,  179,  167,
      144,    0,  198,  704,  749,  749,  749,  703,  239,  690,

      690,  176,  678,  652,  749,  670,  649,  653,  665,  652,
      160,  655,  157,  648,  649,  646,  164,  653,  649,  646,
      643,    0,  127,  647,  654,  647,  644,  634,  634,  636,
      642,  635,  645,  639,  631,  635,  631,  181,  640,  138,
      178,  640,  159,  635,  631,  623,  626,  191,  640,  195,
      630,  633,  749,  749,  259,  240,    0,  749,  749,  271,
      749,  749,  257,  279,  749,  749,  259,  203,  277,  283,
      182,  749,  245,  266,  749,  749,  749,  646,  657,  749,
      749,  749,  749,  749,  749,  749,  749,  749,  646,  647,
      260,  308,  680,  258,  244,  282,  618,  613,  616,  628,

      623,  611,  623,  256,  624,  619,  621,  617,  609,  606,
      614,  601,  616,    0,  602,  606,  609,  594,  597,  600,
      603,  286,  593,  595,  596,  601,  588,  581,    0,  598,
      584,  598,  591,  275,  581,  579,    0,  581,  580,  582,
      589,  590,  574,  572,  572,  574,  583,  582,  578,  580,
      570,  574,  565,  279,  577,  579,  568,  567,  303,  334,
      624,  311,  321,  328,  749,  749,  326,  331,  292,  749,
      317,  749,  749,  749,  749,  320,  319,  749,  749,  598,
      586,  357,  311,  749,  569,  568,  559,  548,    0,  560,
        0,    0,  559,  550,  558,  547,  552,  553,    0,    0,

      546,  546,  556,  542,    0,  546,  551,  546,    0,   73,
        0,  551,  550,  549,  534,  297,  536,  546,    0,  546,
      540,  534,  530,  541,  526,  528,  527,  537,  523,  535,
      525,  529,  528,  533,  532,  518,  520,  528,  526,  524,
      516,  521,  522,  510,  522,    0,  506,  518,  518,  349,
      352,  749,  749,  324,  749,  335,  543,  749,  368,  373,
      567,  518,  500,  500,  501,    0,  328,    0,  502,  503,
      509,  507,  506,  497,  496,    0,  503,  491,  495,  501,
      499,  502,  484,  495,  489,  494,  490,  477,  478,    0,
      494,  475,  475,  486,  480,  481,  476,  484,    0,  483,

      480,  484,  481,  465,  474,  476,  461,  474,  475,    0,
        0,  464,  472,  468,  463,  464,    0,    0,  749,  749,
      749,  468,    0,  453,  465,  465,  454,  448,  448,  460,
        0,  460,  462,  443,    0,  460,    0,    0,  454,  455,
        0,    0,  447,  441,  451,  450,  440,  442,  439,  446,
        0,  439,  446,    0,    0,  439,    0,  436,    0,    0,
        0,  440,  434,  438,  433,  437,    0,    0,    0,  430,
        0,    0,    0,  423,  435,  433,    0,  424,    0,  425,
      424,  423,    0,    0,    0,  421,  419,  415,  424,    0,
      411,  412,    0,  409,  413,    0,    0,  414,    0,  419,

      419,  417,  403,    0,    0,  402,    0,  408,  400,  408,
       27,    0,    0,  411,    0,    0,  397,    0,  410,  404,
        0,  396,    0,    0,  388,  397,  396,  369,  377,  371,
        0,  360,  363,  349,  361,  350,  341,    0,  352,  339,
      353,  350,  336,  336,  347,  335,  345,  331,    0,  343,
      342,    0,  344,  337,    0,  337,    0,  325,  318,    0,
      247,  234,  198,  202,  192,  175,  176,  144,    0,  100,
      104,    0,  749,  415,  419,  423,  428,  432,  434,  439,
      444,  449,  454
    } ;

static yyconst short int yy_def[584] =
    {   0,
      573,    1,  573,  573,  573,  573,  573,  574,  575,  576,
      573,  573,  577,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      576,  576,  573,  573,  573,  573,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  573,  573,
      573,  573,  573,  574,  573,  574,  578,  576,  573,  573,
      573,  573,  573,  577,  577,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  579,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  580,  581,  576,  573,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  573,  573,  573,  582,  578,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  579,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      580,  573,  580,  581,  581,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  582,  573,
      582,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  583,  573,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  583,  573,
      583,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  573,  573,
      573,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,

      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,  576,  576,  576,  576,  576,  576,  576,  576,
      576,  576,    0,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573
    } ;

static yyconst short int yy_nxt[828] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   10,   10,
       10,   10,   10,   10,   10,   31,   32,   10,   10,   10,
       10,   10,   10,   10,   10,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   10,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   10,   58,   10,   59,   60,   61,   62,   65,   69,
       72,   77,  527,   82,   79,   83,   83,   84,   94,   95,
      107,   78,   80,   81,  528,   73,  108,   87,   85,   88,

       88,   97,   98,  102,   87,  113,   93,   93,  103,  125,
      153,   89,  149,  126,  114,   90,   99,  110,   89,   66,
       86,   91,   90,   92,  111,  150,  100,  380,   91,   70,
      112,   71,  118,  115,   89,  116,  101,   65,  381,  122,
       90,   89,  119,  129,  117,  120,  123,   90,   91,  132,
      124,   92,  130,  133,  158,   91,  145,  131,  572,  139,
      134,  154,  140,  141,  571,  573,  135,  146,  136,  142,
       83,   83,  143,   74,  147,  144,  155,  155,   66,  173,
      156,  192,  160,  161,  163,  163,  162,  216,  238,   87,
       75,   88,   88,  169,  217,  169,  164,  165,  170,  170,

      166,  239,  171,   89,  173,  160,  161,  167,  172,  243,
      202,  162,  205,  168,  203,   87,  570,   93,   93,  164,
      165,  206,  193,  274,  244,  166,   89,  171,  210,   89,
      569,  211,  167,   90,  240,  172,  232,  233,  271,   91,
      168,  234,  568,  249,  250,  260,  573,  235,  236,  251,
      274,  241,   89,  255,  194,  256,  567,  252,   90,  253,
      155,  155,  566,  271,  156,  192,   91,  177,  284,  178,
      565,  179,  180,  181,  182,  183,  163,  163,  184,  185,
      275,  186,  187,  188,  564,  262,  261,  262,  264,  265,
      263,  263,  266,  267,  269,  267,  170,  170,  268,  268,

      270,  276,  170,  170,  195,  275,  193,  277,  260,  282,
      282,  264,  265,  283,  563,  272,  360,  266,  273,  269,
      285,  286,  294,  295,  312,  313,  276,  270,  324,  344,
      263,  263,  345,  352,  277,  155,  155,  325,  272,  156,
      263,  263,  350,  273,  350,  268,  268,  351,  351,  261,
      268,  268,  353,  161,  356,  354,  162,  361,  282,  282,
      352,  355,  283,  165,  386,  419,  166,  387,  351,  351,
      420,  351,  351,  360,  282,  282,  161,  353,  283,  356,
      354,  162,  426,  562,  265,  561,  165,  266,  355,  427,
      560,  166,  419,  559,  558,  420,  557,  556,  555,  554,

      553,  552,  551,  550,  549,  548,  547,  265,  546,  545,
      544,  543,  266,  542,  361,   64,   64,   64,   64,   64,
       67,  541,  540,   67,   68,  539,   68,   68,   74,   74,
      538,   74,   74,  157,  537,  157,  157,  174,  174,  191,
      191,  191,  191,  191,  194,  194,  536,  194,  194,  259,
      259,  259,  259,  259,  359,  359,  359,  359,  359,  535,
      534,  533,  532,  531,  530,  529,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,

      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  425,  424,  423,  422,  573,
      421,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,

      389,  388,  385,  384,  383,  382,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  358,  357,  573,  349,  348,  347,
      346,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  293,  292,  291,  290,  289,
      288,  287,  573,  281,  280,  279,  278,  258,  257,  254,
      248,  247,  246,  245,  242,  237,  231,  230,  229,  228,

      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      215,  214,  213,  212,  209,  208,  207,  204,  201,  200,
      199,  198,  197,  196,  195,  190,  189,  176,  175,  159,
      573,  152,  151,  148,  138,  137,  128,  127,  121,  109,
      106,  105,  104,   96,   76,   75,   63,  573,    3,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573
    } ;

static yyconst short int yy_chk[828] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   11,
       12,   17,  511,   20,   19,   20,   20,   21,   26,   26,
       38,   17,   19,   19,  511,   12,   38,   22,   21,   22,

       22,   28,   28,   31,   23,   41,   23,   23,   31,   46,
       60,   22,   56,   46,   41,   22,   30,   40,   23,    8,
       21,   22,   23,   22,   40,   56,   30,  310,   23,   11,
       40,   11,   43,   42,   22,   42,   30,   64,  310,   45,
       22,   23,   43,   49,   42,   43,   45,   23,   22,   50,
       45,   22,   49,   50,   74,   23,   54,   49,  571,   53,
       50,   60,   53,   53,  570,   75,   50,   54,   50,   53,
       83,   83,   53,   75,   54,   53,   65,   65,   64,   91,
       65,  102,   83,   83,   87,   87,   83,  123,  140,   88,
       74,   88,   88,   89,  123,   89,   87,   87,   89,   89,

       87,  140,   90,   88,   91,   83,   83,   88,   90,  143,
      111,   83,  113,   88,  111,   93,  568,   93,   93,   87,
       87,  113,  102,  171,  143,   87,   88,   90,  117,   93,
      567,  117,   88,   93,  141,   90,  138,  138,  168,   93,
       88,  138,  566,  148,  148,  156,  195,  138,  138,  148,
      171,  141,   93,  150,  195,  150,  565,  148,   93,  148,
      155,  155,  564,  168,  155,  191,   93,   99,  194,   99,
      563,   99,   99,   99,   99,   99,  163,  163,   99,   99,
      173,   99,   99,   99,  562,  160,  156,  160,  163,  163,
      160,  160,  163,  164,  167,  164,  169,  169,  164,  164,

      167,  174,  170,  170,  194,  173,  191,  174,  259,  192,
      192,  163,  163,  192,  561,  170,  283,  163,  170,  167,
      196,  196,  204,  204,  222,  222,  174,  167,  234,  254,
      262,  262,  254,  269,  174,  260,  260,  234,  170,  260,
      263,  263,  264,  170,  264,  267,  267,  264,  264,  259,
      268,  268,  271,  263,  277,  276,  263,  283,  282,  282,
      269,  276,  282,  268,  316,  354,  268,  316,  350,  350,
      356,  351,  351,  359,  360,  360,  263,  271,  360,  277,
      276,  263,  367,  559,  351,  558,  268,  351,  276,  367,
      556,  268,  354,  554,  553,  356,  551,  550,  548,  547,

      546,  545,  544,  543,  542,  541,  540,  351,  539,  537,
      536,  535,  351,  534,  359,  574,  574,  574,  574,  574,
      575,  533,  532,  575,  576,  530,  576,  576,  577,  577,
      529,  577,  577,  578,  528,  578,  578,  579,  579,  580,
      580,  580,  580,  580,  581,  581,  527,  581,  581,  582,
      582,  582,  582,  582,  583,  583,  583,  583,  583,  526,
      525,  522,  520,  519,  517,  514,  510,  509,  508,  506,
      503,  502,  501,  500,  498,  495,  494,  492,  491,  489,
      488,  487,  486,  482,  481,  480,  478,  476,  475,  474,
      470,  466,  465,  464,  463,  462,  458,  456,  453,  452,

      450,  449,  448,  447,  446,  445,  444,  443,  440,  439,
      436,  434,  433,  432,  430,  429,  428,  427,  426,  425,
      424,  422,  416,  415,  414,  413,  412,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  398,  397,  396,
      395,  394,  393,  392,  391,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  375,  374,
      373,  372,  371,  370,  369,  365,  364,  363,  362,  361,
      357,  349,  348,  347,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,

      318,  317,  315,  314,  313,  312,  308,  307,  306,  304,
      303,  302,  301,  298,  297,  296,  295,  294,  293,  290,
      288,  287,  286,  285,  281,  280,  261,  258,  257,  256,
      255,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  236,  235,  233,
      232,  231,  230,  228,  227,  226,  225,  224,  223,  221,
      220,  219,  218,  217,  216,  215,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  203,  202,  201,  200,  199,
      198,  197,  193,  190,  189,  179,  178,  152,  151,  149,
      147,  146,  145,  144,  142,  139,  137,  136,  135,  134,

      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      121,  120,  119,  118,  116,  115,  114,  112,  110,  109,
      108,  107,  106,  104,  103,  101,  100,   98,   94,   82,
       66,   58,   57,   55,   52,   51,   48,   47,   44,   39,
       37,   36,   32,   27,   16,   13,    7,    3,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
/*;-*-C-*-; 
** Splint - annotation-assisted static program checker
** Copyright (C) 1994-2003 University of Virginia,
**         Massachusetts Institute of Technology
**
** This program is free software; you can redistribute it and/or modify it
** under the terms of the GNU General Public License as published by the
** Free Software Foundation; either version 2 of the License, or (at your
** option) any later version.
** 
** This program is distributed in the hope that it will be useful, but
** WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
** General Public License for more details.
** 
** The GNU General Public License is available from http://www.gnu.org/ or
** the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
** MA 02111-1307, USA.
**
** For information on splint: splint@cs.virginia.edu
** To report a bug: splint-bug@cs.virginia.edu
** For more information: http://www.splint.org
*/
/*
** cscanner.l
**
** Flex lexer for C.
** Based on a C lexer by Nate Osgood
**    from hacrat@catfish.lcs.mit.edu Mon Jun 14 13:06:32 1993
*/
/*
** Modified by Herbert 08/19/97:
** - added #include for IBM's OS/2 compiler.
** - fixed weird bug with lookup of tmp files (OS/2 and MSDOS only).
*/
/*
** Modified by Mike Smith 
** Corrected missing 'line' in scanf() calls in handleSpecial().
** Without this, I get an error when Splint hits a '#line' directive
** in the pre-pre-processed source files. For safety, I have made these
** conditional on OS2 and MSDOS because I don't understand why noone else
** has seen this problem.
**
** Modified by Mike Smith, 4th June 1997
** Finally resolved the #line problem.  The scanf() calls have been fixed to
** allow the following #line forms:-
**
**        #line 123 "filename"
**        #line 123
**        # 123 "filename"
**        # 123
**
** The last two are generated by the GNU pre-processor, apparently
*/
# include "splintMacros.nf"
# if defined(OS2) && defined(__IBMC__)
   /* needed for isatty()... */
# include <io.h>
# else

/*
** Win32 doesn't have unistd.h
*/

# ifndef WIN32
# include <unistd.h>
# endif

# endif

# include "basic.h"

# include "cscannerHelp.h"
# include "cgrammar.h"
# include "cgrammar_tokens.h"
# include "osd.h"

/*@notfunction@*/
# define yyinput() (incColumn (), getc (yyin))

# include "flex.head"


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 574 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 749 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{ llfatalerror (cstring_makeLiteral ("Comment in pre-processor output")); }
	YY_BREAK
case 2:
YY_RULE_SETUP
{  
                 context_saveLocation (); 
                 cscannerHelp_setTokLength (longUnsigned_toInt (mstring_length (yytext))); 

                 if (cscannerHelp_processHashIdentifier 
		     (cscannerHelp_makeIdentifier (yytext + 1)))
                   {
		     return cscannerHelp_returnString (cstring_makeLiteral ("\"\""));
		   }
                 else
                   { 
		     if (cscannerHelp_handleSpecial (yytext)) 
                       { 
			 cscannerHelp_setTokLength (1); 
			 return cscannerHelp_returnToken (0); 
		       }
		   }
                } 
	YY_BREAK
case 3:
YY_RULE_SETUP
{ if (cscannerHelp_handleSpecial (yytext)) 
                    { 
                       cscannerHelp_setTokLength (1); return cscannerHelp_returnToken (0); 
                     }
                }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); return cscannerHelp_returnToken (CTOK_ELIPSIS); }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnToken (BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (CONTINUE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (7); return cscannerHelp_returnToken (DEFAULT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (2); return cscannerHelp_returnToken (DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (CELSE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); return cscannerHelp_returnToken (CFOR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (GOTO); }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (2); return cscannerHelp_returnToken (CIF); }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (RETURN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (CSIZEOF); }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (COFFSETOF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (SWITCH); }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnToken (WHILE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (VA_ARG); }   
	YY_BREAK
case 20:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (VA_DCL); }   
	YY_BREAK
case 21:
YY_RULE_SETUP
{ 
                  /* gcc extension...this might not be appropriate */
                  cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (QINLINE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (CSTRUCT); }  
	YY_BREAK
case 23:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (7); return cscannerHelp_returnToken (CTYPEDEF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnToken (CUNION); }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (CENUM); }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnType (CVOID, ctype_void); }
	YY_BREAK
case 27:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); return cscannerHelp_returnType (CINT, ctype_int); }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnType (CDOUBLE, ctype_double); }
	YY_BREAK
case 29:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnType (CGCHAR, ctype_char); }
	YY_BREAK
case 30:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnType (CGFLOAT, ctype_float); }
	YY_BREAK
case 31:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (QLONG); }
	YY_BREAK
case 32:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnToken (QSHORT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (QUNSIGNED); }
	YY_BREAK
case 34:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (QSIGNED); }
	YY_BREAK
case 35:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (QVOLATILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (5); return cscannerHelp_returnToken (QCONST); }
	YY_BREAK
case 37:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (QRESTRICT); }
	YY_BREAK
/* some systems expect this! [gack!] */ 
case 38:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (7); return cscannerHelp_returnToken (QCONST); }
	YY_BREAK
case 39:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (QEXTERN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); return cscannerHelp_returnToken (QAUTO); }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (8); return cscannerHelp_returnToken (QREGISTER); }
	YY_BREAK
case 42:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); return cscannerHelp_returnToken (QSTATIC); }
	YY_BREAK
case 43:
YY_RULE_SETUP
{ return cscannerHelp_returnExpr (cscannerHelp_processString ()); }
	YY_BREAK
case 44:
YY_RULE_SETUP
{ return cscannerHelp_returnExpr (cscannerHelp_processWideString ()); }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QOUT)); }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QIN)); }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QPARTIAL)); }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QSPECIAL)); }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QANYTYPE)); }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QINTEGRALTYPE)); }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QUNSIGNEDINTEGRALTYPE)); }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QSIGNEDINTEGRALTYPE)); }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QKEEP)); }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QNULL)); } 
	YY_BREAK
case 55:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QNOTNULL)); } 
	YY_BREAK
case 56:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QISNULL)); } 
	YY_BREAK
case 57:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QTRUENULL)); } 
	YY_BREAK
case 58:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QFALSENULL)); } 
	YY_BREAK
case 59:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QTRUENULL)); } 
	YY_BREAK
case 60:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QFALSENULL)); } 
	YY_BREAK
case 61:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QRELNULL)); }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QRELDEF)); }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QEXPOSED)); }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QNEWREF)); }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QTEMPREF)); }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QKILLREF)); }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QREFCOUNTED)); }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QCHECKED)); }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QCHECKMOD)); }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QCHECKEDSTRICT)); }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QUNCHECKED)); }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QONLY)); }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QOWNED)); }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QOBSERVER)); }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QDEPENDENT)); }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QUNUSED)); }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QEXTERNAL)); }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QSEF)); }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QSHARED)); }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QYIELD)); }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QUNDEF)); }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QKILLED)); }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QNULLTERMINATED));}
	YY_BREAK
case 84:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QMAXSET));}
	YY_BREAK
case 85:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QMAXREAD));}
	YY_BREAK
case 86:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QMAXSET));}
	YY_BREAK
case 87:
YY_RULE_SETUP
{ return (cscannerHelp_processSpec (QMAXREAD));}
	YY_BREAK
case 88:
YY_RULE_SETUP
{ int tok = cscannerHelp_processTextIdentifier (yytext);
                              if (tok != BADTOK)
				{
				  return (tok);
				}
			    }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
                          return cscannerHelp_returnInt (ctype_int, cscannerHelp_processHex ());  /* evs 2000-05-17 was ctype_uint */
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_lint, cscannerHelp_processHex ()); }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_llint, cscannerHelp_processHex ()); }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
                          return cscannerHelp_returnInt (ctype_uint, cscannerHelp_processHex ()); }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_ulint, cscannerHelp_processHex ()); }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processHex ()); }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processHex ()); }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			  return cscannerHelp_returnInt (ctype_int, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 97:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
		 	  return cscannerHelp_returnInt (ctype_uint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 98:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
 		          return cscannerHelp_returnInt (ctype_lint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 99:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
 		          return cscannerHelp_returnInt (ctype_llint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 100:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	   	          return cscannerHelp_returnInt (ctype_ulint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 101:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	   	          return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 102:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	   	          return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processOctal ()); } 
	YY_BREAK
case 103:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
		         return cscannerHelp_returnInt (ctype_int, cscannerHelp_processDec ()); } 
	YY_BREAK
case 104:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
		         return cscannerHelp_returnInt (ctype_uint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 105:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	      	         return cscannerHelp_returnInt (ctype_lint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 106:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	      	         return cscannerHelp_returnInt (ctype_llint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 107:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	    	         return cscannerHelp_returnInt (ctype_ulint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 108:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	    	         return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 109:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
	    	         return cscannerHelp_returnInt (ctype_ullint, cscannerHelp_processDec ()); } 
	YY_BREAK
case 110:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
                         return cscannerHelp_returnChar (cscannerHelp_processChar ()); }
	YY_BREAK
case 111:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
                         return cscannerHelp_returnChar (cscannerHelp_processChar ()); }
	YY_BREAK
case 112:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			 return cscannerHelp_returnFloat (ctype_float, cscannerHelp_processFloat ()); }
	YY_BREAK
case 113:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			 return cscannerHelp_returnFloat (ctype_ldouble, cscannerHelp_processFloat ()); }
	YY_BREAK
case 114:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
			 return cscannerHelp_returnFloat (ctype_double, cscannerHelp_processFloat ()); }
	YY_BREAK
case 115:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				return cscannerHelp_returnFloat (ctype_float, cscannerHelp_processFloat ()); }
	YY_BREAK
case 116:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				return cscannerHelp_returnFloat (ctype_ldouble, cscannerHelp_processFloat ()); }
	YY_BREAK
case 117:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				return cscannerHelp_returnFloat (ctype_double, cscannerHelp_processFloat ()); }
	YY_BREAK
case 118:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				  return cscannerHelp_returnFloat (ctype_float, cscannerHelp_processFloat ()); }
	YY_BREAK
case 119:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				  return cscannerHelp_returnFloat (ctype_ldouble, cscannerHelp_processFloat ()); }
	YY_BREAK
case 120:
YY_RULE_SETUP
{ cscannerHelp_setTokLengthT (mstring_length (yytext)); 
				  return cscannerHelp_returnFloat (ctype_double, cscannerHelp_processFloat ()); }
	YY_BREAK
case 121:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (RIGHT_ASSIGN, 3); }
	YY_BREAK
case 122:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (LEFT_ASSIGN, 3); }
	YY_BREAK
case 123:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (ADD_ASSIGN, 2); }
	YY_BREAK
case 124:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (SUB_ASSIGN, 2); }
	YY_BREAK
case 125:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (MUL_ASSIGN, 2); }
	YY_BREAK
case 126:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (DIV_ASSIGN, 2); }
	YY_BREAK
case 127:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (MOD_ASSIGN, 2); }
	YY_BREAK
case 128:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (AND_ASSIGN, 2); }
	YY_BREAK
case 129:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (XOR_ASSIGN, 2); }
	YY_BREAK
case 130:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (OR_ASSIGN, 2); }
	YY_BREAK
case 131:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (RIGHT_OP, 2); }
	YY_BREAK
case 132:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (LEFT_OP, 2); }
	YY_BREAK
case 133:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (INC_OP, 2); }
	YY_BREAK
case 134:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (DEC_OP, 2); }
	YY_BREAK
case 135:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (ARROW_OP, 2); }
	YY_BREAK
case 136:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (AND_OP, 2); }
	YY_BREAK
case 137:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (OR_OP, 2); }
	YY_BREAK
case 138:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TCAND, 2); }
	YY_BREAK
case 139:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (LE_OP, 2); }
	YY_BREAK
case 140:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (GE_OP, 2); }
	YY_BREAK
case 141:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (EQ_OP, 2); }
	YY_BREAK
case 142:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (NE_OP, 2); }
	YY_BREAK
case 143:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TSEMI, 1); }
	YY_BREAK
case 144:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TLBRACE, 1); }
	YY_BREAK
case 145:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TRBRACE, 1); }
	YY_BREAK
case 146:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TCOMMA, 1); }
	YY_BREAK
case 147:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TCOLON, 1); }
	YY_BREAK
case 148:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TASSIGN, 1); }
	YY_BREAK
case 149:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TLPAREN, 1); }
	YY_BREAK
case 150:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TRPAREN, 1); }
	YY_BREAK
case 151:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TLSQBR, 1); }
	YY_BREAK
case 152:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TRSQBR, 1); }
	YY_BREAK
case 153:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TDOT, 1); }
	YY_BREAK
case 154:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TAMPERSAND, 1); }
	YY_BREAK
case 155:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TEXCL, 1); }
	YY_BREAK
case 156:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TTILDE, 1); }
	YY_BREAK
case 157:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TMINUS, 1); }
	YY_BREAK
case 158:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TPLUS, 1); }
	YY_BREAK
case 159:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TMULT, 1); }
	YY_BREAK
case 160:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TDIV, 1); }
	YY_BREAK
case 161:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TPERCENT, 1); }
	YY_BREAK
case 162:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TLT, 1); }
	YY_BREAK
case 163:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TGT, 1); }
	YY_BREAK
case 164:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TCIRC, 1); }
	YY_BREAK
case 165:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TBAR, 1); }
	YY_BREAK
case 166:
YY_RULE_SETUP
{ return cscannerHelp_returnTokenLength (TQUEST, 1); }
	YY_BREAK
case 167:
YY_RULE_SETUP
{ incColumn (); }
	YY_BREAK
case 168:
YY_RULE_SETUP
{ int tok = cscannerHelp_handleNewLine (); 
                  if (tok != BADTOK) return tok; }
	YY_BREAK
case 169:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (6); 
		  
		  if (cscannerHelp_processMacro ()) {
		    if (context_inIterDef ()) 
		      { 
			return cscannerHelp_returnToken (LLMACROITER); 
		      }
		    if (context_inIterEnd ())
		      {
			return cscannerHelp_returnToken (LLMACROEND); 
		      }
		    if (context_inMacro ())
		      {
			return cscannerHelp_returnToken (LLMACRO); 
		      }
		  }
		}
	YY_BREAK
case 170:
YY_RULE_SETUP
{ if (context_inHeader () || context_inFunction ())
		    { 
		      cscannerHelp_handleMacro ();
		    }
                  else
		    {
		      int nspchar = cscannerHelp_ninput ();
		      int nspaces;

		      /* 
		      ** This is a hack to get the column number correct.
		      */

		      llassert (nspchar >= '0' && nspchar <= '9');
		      
		      nspaces = nspchar - '0';

		      cscannerHelp_setTokLength (5 + nspaces); 
		      
		      if (cscannerHelp_processMacro ()) 
			{
			  DPRINTF (("Here we are: %s", context_unparse ()));
			  
			  if (context_inIterDef ()) 
			    {
			      return cscannerHelp_returnToken (LLMACROITER); 
			    }
			  if (context_inIterEnd ())
			    {
			      return cscannerHelp_returnToken (LLMACROEND); 
			    }
			  if (context_inMacro ())
			    { 
			      return cscannerHelp_returnToken (LLMACRO); 
			    }
			}
		    }
		}
	YY_BREAK
case 171:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); lldiagmsg (ctype_unparseTable ()); }
	YY_BREAK
case 172:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (4); lldiagmsg (message ("Access types: %q", typeIdSet_unparse (context_fileAccessTypes ()))); }
	YY_BREAK
case 173:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); 
		  lldiagmsg (message ("%q: *** marker ***", fileloc_unparse (g_currentloc)));
		}
	YY_BREAK
case 174:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printLocal (); }
	YY_BREAK
case 175:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); lldiagmsg (usymtab_unparseAliases ()); }
	YY_BREAK
case 176:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); lldiagmsg (context_unparse ()); }
	YY_BREAK
case 177:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); lldiagmsg (context_unparseClauses ()); }
	YY_BREAK
case 178:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printGuards (); }
	YY_BREAK
case 179:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printOut (); }
	YY_BREAK
case 180:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printAll (); }
	YY_BREAK
case 181:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printComplete (); }
	YY_BREAK
case 182:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); usymtab_printTypes (); }
	YY_BREAK
case 183:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); lldiagmsg (usymtab_unparseStack ()); }
	YY_BREAK
case 184:
YY_RULE_SETUP
{ cscannerHelp_setTokLength (3); 
		  lldiagmsg (message ("Can modify: %q", 
				  sRefSet_unparse (context_modList ()))); 
		}
	YY_BREAK
case 185:
YY_RULE_SETUP
{ /* BEFORE_COMMENT_MARKER */
                  int tok; 
		  incColumn (); incColumn ();
		  tok = cscannerHelp_handleLlSpecial (); 

		  if (tok != BADTOK)
		    {
		      if (tok == CANNOTATION) {
			return (tok);
		      } else {
			/* Beware - this bashes yylval! */
			return cscannerHelp_returnToken (tok); 
		      }
		    }
		}
	YY_BREAK
case 186:
YY_RULE_SETUP
{ /* AFTER_COMMENT_MARKER */ 
                  cscannerHelp_setTokLength (2);
		  cscannerHelp_exitSpecPart ();
		  return cscannerHelp_returnToken (QENDMACRO); }
	YY_BREAK
case 187:
YY_RULE_SETUP
{ incColumn (); cscannerHelp_setContinueLine (); }
	YY_BREAK
case 188:
YY_RULE_SETUP
{ incColumn (); 
                  if ((int) *yytext == 13 ) {
		     ;
                  } else {
		    voptgenerror
		      (FLG_SYNTAX, 
		       message ("Invalid character (ascii: %d), skipping character",
				(int)(*yytext)),
		       g_currentloc);
		  }
		}
	YY_BREAK
case 189:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 574 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 574 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 573);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


/*
** These need to go here, after flex-generated code defined input and unput.
*/

int cscanner_input (void)
{
  return input (); /* input is a static procedure defined by flex-generated code */
}

void cscanner_unput (int c)
{
  unput (c); /* unput is a static procedure defined by flex-generated code */
}



/*
** Resets flags set by flex.head.
*/


/*@=allmacros@*/
/*@=pred@*/
/*@=globstate@*/
/*@=null@*/
/*@=boolint@*/
/*@=charint@*/
/*@=macrospec@*/
/*@=macroredef@*/
/*@=exitarg@*/
/*@=compdef@*/
/*@=uniondef@*/
/*@=ignorequals@*/
/*@=noreturn@*/
/*@=mustfree@*/
/*@=compdestroy@*/
/*@=branchstate@*/
/*@=unreachable@*/
/*@=varuse@*/
/*@=fcnuse@*/
/*@=exportlocal@*/
/*@=evalorderuncon@*/
/*@=exportheader@*/
/*@=redecl@*/
/*@=loopswitchbreak@*/
/*@=switchswitchbreak@*/
/*@=sizeoftype@*/
/*@=czechfcns@*/
/*@=noparams@*/
/*@=ansireserved@*/
/*@=ifblock@*/
/*@=whileblock@*/
/*@=forblock@*/
/*@=elseifcomplete@*/
/*@=ptrnegate@*/
/*@=onlytrans@*/
/*@=temptrans@*/
/*@=immediatetrans@*/
/*@=namechecks@*/
/*@=matchanyintegral@*/
/*@=statictrans@*/
/*@=compmempass@*/
/*@=forempty@*/
/*@=evalorder@*/
/*@=retalias@*/
/*@=redecl@*/
/*@=retvalother@*/

# ifdef OSF
# define __GNUC__
# endif

