/* config.h.  Generated by configure.  */
/* config.hin.  Generated from configure.ac by autoheader.  */

/*constmacros@*/

/* build */
#define BUILD "i686-pc-linux-gnu"

/* build_alias */
#define BUILD_ALIAS ""

/* build_cpu */
#define BUILD_CPU "i686"

/* build_os */
#define BUILD_OS "linux-gnu"

/* build_vendor */
#define BUILD_VENDOR "pc"

/* The directory where Splint's library files live */
#define DEFAULT_LARCHPATH ".:/usr/local/share/splint/lib:/home/mkx/splint-3.1.1/lib:"

/* Splint's imports directory */
#define DEFAULT_LCLIMPORTDIR ".:/usr/local/share/splint/imports:/home/mkx/splint-3.1.1/imports"

/* system include directory */
#define GCC_INCLUDE_DIR "/usr/include"

/* alternate include directory */
#define GCC_INCLUDE_DIR2 "/usr/local/include"

/* host */
#define HOST "i686-pc-linux-gnu"

/* host_alias */
#define HOST_ALIAS ""

/* host_cpu */
#define HOST_CPU "i686"

/* host_os */
#define HOST_OS "linux-gnu"

/* host_vendor */
#define HOST_VENDOR "pc"

/* String describing who compiled this binary and how */
#define LCL_COMPILE "Compiled using gcc -g -O2 on Linux debian 4.9.0-3-686-pae #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) i686 GNU/Linux by mkx"

/* Splint's version number */
#define LCL_PARSE_VERSION "Splint 3.1.1"

/* Define to disable support LCL files */
/* #undef NOLCL */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "splint-bug@splint.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Splint"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Splint 3.1.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "splint"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.1.1"

/* Splint's version number and configure/build date */
#define SPLINT_VERSION "Splint 3.1.1 --- 22 Feb 2020"

/* The system's main include directory */
#define SYSTEM_LIBDIR "/usr/local/include"

/* target */
#define TARGET "i686-pc-linux-gnu"

/* target_alias */
#define TARGET_ALIAS ""

/* target_cpu */
#define TARGET_CPU "i686"

/* target_os */
#define TARGET_OS "linux-gnu"

/* target_vendor */
#define TARGET_VENDOR "pc"

/* uname output */
#define UNAME "Linux"

/* Define if you're on a Unixy system */
#define UNIX 1

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1

/* needed to expose mode_t on some machines */
/* #undef _ALL_SOURCE */

/*@=constmacros@*/
